export const PARTICIPANT_ADDED = "PARTICIPANT_ADDED";
export const PARTICIPANT_REMOVED = "PARTICIPANT_REMOVED";
export const CUSTOMER = "CUSTOMER";

export const NOTIFICATIONS = {
    WAITING_FOR_AGENT:'WAITING_FOR_AGENT',
    AGENT_CONNECTED:'AGENT_CONNECTED',
    CONNECTED:"CONNECTED",
    DISCONNECTED:"DISCONNECTED", 
    CONNECTING:"CONNECTING",
    ENGAGEMENT_ERROR:'ENGAGEMENT_ERROR',
    IDLE_TIMEOUT_EXPIRED:'IDLE_TIMEOUT_EXPIRED',
    SESSION_EXPIRED:"SESSION_EXPIRED",
    DISCONNECTED2:"DISCONNECTED2",
    ENGAGEMENT_TERMINATED:"ENGAGEMENT_TERMINATED"
}