export const MINIMIZE_CHAT_POPUP='MINIMIZE_CHAT_POPUP';
export const MAXIMIZE_CHAT_POPUP='MAXIMIZE_CHAT_POPUP';
export const SET_CHAT_CONFIG='SET_CHAT_CONFIG';
export const OPEN_EXIT_DIALOG='OPEN_EXIT_DIALOG';
export const CLOSE_EXIT_DIALOG='CLOSE_EXIT_DIALOG';
export const SET_CHAT_WINDOW_HEIGHT='SET_CHAT_WINDOW_HEIGHT';
export const SET_TRANSLATIONS='SET_TRANSLATIONS';
export const SET_LANG='SET_LANG';

